version: '{build}'
skip_tags: true
image: Visual Studio 2022
build_script:
- ps: ./Build.ps1
test: off
artifacts:
- path: .artifacts/piggy-*.tar.gz
- path: .artifacts/piggy-*.zip
- path: .artifacts/Datalust.Piggy.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: SpQqgQJy2iM/h7INGH2/MF/yo0K30snzKNogLkXRM0LNzzDXPlKdIvkYTrl6uuFn
  skip_symbols: true
  on:
    branch: /^(main|dev)$/
- provider: GitHub
  auth_token:
    secure: Bo3ypKpKFxinjR9ShkNekNvkob2iklHJU+UlYyfHtcFFIAa58SV2TkEd0xWxz633
  artifact: /piggy-.*\.(zip|tar\.gz)/
  tag: v$(appveyor_build_version)
  on:
    branch: main
