version: 3.0.{build}
skip_tags: true
image: Visual Studio 2019
build_script:
- ps: ./Build.ps1
test: off
artifacts:
- path: artifacts/piggy-*.tar.gz
- path: artifacts/piggy-*.zip
- path: artifacts/Datalust.Piggy.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: qFvoUBcJYV2z0Q8x38cjFDdSdpPclcynF5/FcZbNmSDfQhqTy87D5vBZIp3HaO0I
  skip_symbols: true
  on:
    branch: main
- provider: GitHub
  auth_token:
    secure: Bo3ypKpKFxinjR9ShkNekNvkob2iklHJU+UlYyfHtcFFIAa58SV2TkEd0xWxz633
  artifact: /piggy-.*\.(msi|tar\.gz)/
  tag: v$(appveyor_build_version)
  on:
    branch: main
